### PR TITLE
Responsive mode

### PR DESCRIPTION
**Pull request by darenju**
This PR introduces the responsive mode for the component.

@enikolas, would you confirm it works, I have tried in my browser, seems to work properly.

To try:
- Use a create-react-app or anything to test the component
- `npm run build` in the project directory
- `ln -s` the `dist/index.js` file in your test directory, then import it

### CODE REVIEW

**Comment by enikolas** [comment]
Damn, you are so fast bro!

I'll give it a try when I get at home. Now I'm at work, kind of busy. =/

**Comment by darenju** [comment]
Actually it was much faster than I expected. I simply removed the `height` and `width` references and used absolute positioning to place everything correctly.

**Comment by enikolas** [comment]
Ok, now I have test it.

It works in some sort of way. But it acts oddly when using images as an entire page.

I'll try to set up a demo project, so you can see what is happening with me.

Basically, if the image has a height higher than the screen, it gets cropped (without the ability to scroll down).

I need to try to use HTML instead of pure image, as image isn't that responsive out-of-the-box.

**Comment by enikolas** [comment]
Here is a dummy project to demo you the issue itself: [react-flip-page-demo](https://github.com/enikolas/react-flip-page-demo)

**Comment by darenju** [comment]
The trick to use images as full page is to place the image in a container. Because the container will receive some style to place it correctly and cut it into two halves.

So if you specify a height on the image, it will collide with `top: 0;` and `bottom: 0;`.

Check [this page](https://darenju.me/react-flip-page/responsive) to see.

**Comment by enikolas** [comment]
Thank you. I'll take a look on that and check if I can made it work in my real example.

Today after work, I plan to continue on the unit test. Hopefully, I'll be able to cover it to 100% by today.

**Pull request merged**
