### PR TITLE
Fix npm packaging

### PR DESCRIPTION
**Pull request by enikolas**
- Remove the ```.npmignore``` as it start to get to verbose
- Add inside ```package.json``` the section ```files``` which specifiy the only directory needed, beside the already default files NPM requires (like package.json, README.md, CHANGELOG.md, ...

---

To test this, run the following commands:

(ensure to not have unversioned files in your local directory first):

```
git clean -fd .
npm install
npm run build
npm pack
```

Then, take a look at the package generated.

---

**PS.:** Sorry, I forgot to run ```npm pack``` before sending the PR, my bad.

### CODE REVIEW

**Comment by darenju** [comment]
That's what I started doing. Trying here on my own, but it should be good. 👍

**Comment by darenju** [comment]
Regarding [this page](https://github.com/npm/npm/wiki/Files-and-Ignores#details-1), I am not sure that if the build file is included in `files` array and in `.gitignore`, it will end up included in the package…

`npm pack` with these changes gives a correct package locally, but when installed from NPM, the build file is not present.

**Comment by darenju** [comment]
Issue resolved. I had included the `skip_cleanup: false` option in `.travis.yml`, causing Travis to not publish the build file…

**Comment by enikolas** [comment]
Oh my gosh, really?!

How odd!

Travis uses to ask to leave the ```skip_cleanup: true``` on deploy stages, as they use to [remove all generated files](https://docs.travis-ci.com/user/deployment/npm/#Releasing-build-artifacts).

But well, if that solved your issue. Cheers!!!

**Comment by darenju** [comment]
I actually wrote it myself, because I did not understand the docs properly.

Should have read it more in details before making the build process. 😄

**Pull request merged**
