### PR TITLE
Add `loopForever` option

### PR DESCRIPTION
**Pull request by hconklin**
When set to `true`, `loopForever` will cause a transition to the first
slide when attempting to go to the next page on the last one (and
likewise for transitioning to the previous from the first). The default
value for `loopForever` is `false`, which preserves the original
behavior.

### CODE REVIEW

**Comment by darenju** [comment]
Hello @hconklin! Thank you for your contribution. I will now test your work on a separate branch before actually merging it into `master`.

Keep in mind it is good practice to work on a separate branch to make merging easier later. :wink:

**Comment by darenju** [comment]
Your work has been merged into `master` branch. Thank you for your contribution!

**Comment by hconklin** [comment]
Sorry,  You are correct, I should have been using a branch.

This works very well.  Thanks for the effort.


On Sep 2, 2017, at 2:17 PM, Julien Fradin <notifications@github.com> wrote:

Hello @hconklin <https://github.com/hconklin>! Thank you for your contribution. I will now test your work on a separate branch before actually merging it into master.

Keep in mind it is good practice to work on a separate branch to make merging easier later. 😉

**Comment by darenju** [comment]
There was a little bug in `_beforeItem` and `_afterItem`, you overrode the `lastComponent` part so I added a complementary check.

The package is now published on version 0.9.0

**Pull request merged**
